name: practice2
on:
  workflow_dispatch:
jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
        - name: step1
          run: echo 'step1'
  jobs2:
    needs: jobs1
    runs-on: ubuntu-latest
    steps:
        - name: step2
          run: echo 'step2'
  jobs3:
    runs-on: ubuntu-latest
    steps:
        - name: step3
          run: echo 'step3'