name: mockuo to GitHubPages

on:
  push:
    branches:
      - main

env:
  cache-version: v1

jobs:
  release:
    name: Project Build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # checkout resource
      - name: Check out code
        uses: actions/checkout@v4
      # node install
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      # lib install
      - name: Install dependencies
        run: npm ci
      # build static contents
      - name: Build
        run: npm run build
      # deploy 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
